services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: sber
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app-network

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app-container
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: sber
      MYSQL_USER: root
      MYSQL_PASSWORD: qwerty
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    command: ["sh", "-c", "until nc -z mysql 3306; do echo waiting for mysql; sleep 5; done; npm start"]
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
